# Generated by Django 2.0.2 on 2018-03-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
